In [36]:
import warnings

warnings.filterwarnings("ignore")

In [1]:
import faiss

### Loading preprocessed data

In [18]:
import pandas as pd

jobs = pd.read_csv('preprocessed_jobs.csv', usecols=['job_title', 'description', 'requirements', 'career_level', 'prep_title_description'])
jobs.head()

job_title  \
0                 Senior Developer Relations Manager   
1                            Costing Manager - Cairo   
2                                 Banquet Supervisor   
3                  Trade Finance & Credit Collection   
4  Taste & Wellbeing Creative Marketing Associate...   

                                         description  \
0  Senior Developer Relations Manager page is loa...   
1  Supervise, design and implement a consistently...   
2  Mandarin Oriental Hotel GroupMandarin Oriental...   
3  About Us Alfa Laval is a leading global provid...   
4  Join us and celebrate the beauty of human expe...   

                                        requirements  \
0                                                NaN   
1  <ul>\n<li>Bachelor’s degree in Accounting</li>...   
2                                                NaN   
3                                                NaN   
4                                                NaN   

                career_level  \
0              Not specified   
1                    Manager   
2  Experienced (Non-Manager)   
3              Not specified   
4              Not specified   

                              prep_title_description  
0  Senior Developer Relations Manager {title} Sen...  
1  Costing Manager - Cairo {title} Supervise, des...  
2  Banquet Supervisor {title} Mandarin Oriental H...  
3  Trade Finance & Credit Collection {title} Abou...  
4  Taste & Wellbeing Creative Marketing Associate...

In [19]:
prep_title_description = list(jobs["prep_title_description"])

print(len(prep_title_description))

40000


### Loading saved embeddings

In [5]:
import numpy as np

embeddings = np.load('embeddings.npy')

print(embeddings.shape)

(40000, 384)


In [7]:
embed_length = embeddings.shape[1]

index = faiss.IndexFlatL2(embed_length)
index.is_trained

True

In [8]:
# Add the embeddings to the index
index.add(embeddings)

# Check the total number of embeddings in the index
index.ntotal

40000

In [14]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

In [15]:
query = ['Machine Learning Engineer']
# Vectorize the query string
query_embedding = model.encode(query)

In [21]:
%%time

# Select Top k
k = 3
scores, index_vals = index.search(query_embedding, k)

print(index_vals)
print(scores)

[[35213 11345  5383]]
[[0.59074473 0.612579   0.61495036]]
CPU times: total: 15.6 ms
Wall time: 20 ms


In [26]:
for pred_indexes in index_vals[0]:
    print(prep_title_description[pred_indexes])
    print()

Machine Learning Engineer {title} Showcase your software engineering talents using ML-powered profiles. Loved by 11k+ engineers! Backed by Antler.The RoleYou Will Be Responsible ForDeveloping scripts to process structured and unstructured data.Recommending, developing and implementing ways to improve data reliability, efficiency and quality.Supporting translation of data business needs into technical system requirements.Working with stakeholders to understand needs in order with respect to data structure, availability, scalability and accessibility.Developing high-quality code to build and deploy machine learning models.Ideal ProfileYou possess a degree in Computer Science, Applied Mathematics, Engineering or related field.You have at least 1 year experience, ideally within a Data Engineer role.Demonstrated experience working with large and complex data sets as well as experience analyzing volumes of data.You are a strong networker & relationship builderYou pay strong attention to deta

### Decreasing response time by using Nearest Neighbor search

In [27]:
# Preparing for training
num_centroids = 5
quantizer = faiss.IndexFlatL2(embed_length)
index = faiss.IndexIVFFlat(quantizer, embed_length, num_centroids)

index.train(embeddings) # train using our embeddings array

index.is_trained

True

In [28]:
index.add(embeddings) # Add the embeddings to the index
index.ntotal # Check how many embeddings are in the index

40000

In [30]:
%%time

# Select Top k
k = 3
scores, index_vals = index.search(query_embedding, k)

print(index_vals)
print(scores)

[[35213 11345  5383]]
[[0.59074473 0.612579   0.61495036]]
CPU times: total: 15.6 ms
Wall time: 0 ns


In [31]:
for pred_indexes in index_vals[0]:
    print(prep_title_description[pred_indexes])
    print()

Machine Learning Engineer {title} Showcase your software engineering talents using ML-powered profiles. Loved by 11k+ engineers! Backed by Antler.The RoleYou Will Be Responsible ForDeveloping scripts to process structured and unstructured data.Recommending, developing and implementing ways to improve data reliability, efficiency and quality.Supporting translation of data business needs into technical system requirements.Working with stakeholders to understand needs in order with respect to data structure, availability, scalability and accessibility.Developing high-quality code to build and deploy machine learning models.Ideal ProfileYou possess a degree in Computer Science, Applied Mathematics, Engineering or related field.You have at least 1 year experience, ideally within a Data Engineer role.Demonstrated experience working with large and complex data sets as well as experience analyzing volumes of data.You are a strong networker & relationship builderYou pay strong attention to deta

### Generation

In [ ]:
# from transformers import AutoTokenizer, AutoModelForCausalLM

# model_name = "EleutherAI/gpt-j-6B"
# tokenizer = AutoTokenizer.from_pretrained(model_name)
# model = AutoModelForCausalLM.from_pretrained(model_name)

In [ ]:
from openai import OpenAI

In [66]:
api_key = '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'
OpenAI.api_key = api_key

In [67]:
prmpt = f"""
You will be provided with a job title: 
{query[0]}
Provide personal career advice basedon this job title
"""

In [71]:
client = OpenAI(api_key=api_key)

completion = client.chat.completions.create(
  model = "gpt-4o-mini",
  messages = prompt
)

print(completion.choices[0].message.content)

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

### integrate

In [ ]:
def retrieve_top_k_jobs(query, k=3):
    # Vectorize the user query
    query_embedding = model.encode([query])

    # Perform a search in the FAISS index to retrieve top k job descriptions
    scores, index_vals = index.search(query_embedding, k)

    # Retrieve the top k job descriptions
    top_jobs = [job_descriptions[i] for i in index_vals[0]]

    print("Top job descriptions matching the query:")
    for i, job in enumerate(top_jobs):
        print(f"{i+1}. {job}")
    
    return top_jobs

def generate_recommendation(top_jobs):
    # Create a summary of the top job descriptions
    job_summary = "\n".join(top_jobs)
    prompt = f"Based on the following job search results, craft a personalized job recommendation:\n\n{job_summary}\n\nRecommendation:"

    # Tokenize the prompt
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=1024)

    # Generate the response
    outputs = model.generate(inputs["input_ids"], max_length=200)

    # Decode and return the generated recommendation
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

def process_query_and_generate_recommendation(query, k=3):
    # Retrieve the top k job descriptions
    top_jobs = retrieve_top_k_jobs(query, k)

    # Generate a personalized recommendation based on the retrieved jobs
    recommendation = generate_recommendation(top_jobs)
    
    print("\nGenerated Recommendation:")
    print(recommendation)
    
    return recommendation

In [ ]:
query = ['Machine Learning Engineer']
# Vectorize the query string
recommendation = process_query_and_generate_recommendation(query)
print(recommendation)